
name: release

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version'
        # Default value if no value is explicitly provided
        default: '1.0.0'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          generateReleaseNotes: true

  build-windows:
    runs-on: windows-latest
    needs: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and upload
        shell: pwsh
        run: ./gradlew clean packageForWindows --stacktrace --info --no-daemon -x test
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/*.*
          tag: ${{ github.event.inputs.version }}
          overwrite: true
          file_glob: true
      - uses: actions/upload-artifact@v3
        with:
          name: target-windows
          path: ./build/

  build-mac:
    runs-on: macos-latest
    needs: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and upload
        shell: pwsh
        run: ./gradlew clean packageForMac --stacktrace --info --no-daemon -x test
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/*.*
          tag: ${{ github.event.inputs.version }}
          overwrite: true
          file_glob: true
      - uses: actions/upload-artifact@v3
        with:
          name: target-mac
          path: ./build/

  build-linux:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and upload
        shell: pwsh
        run: ./gradlew clean packageForLinux --stacktrace --info --no-daemon -x test
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/*.*
          tag: ${{ github.event.inputs.version }}
          overwrite: true
          file_glob: true
      - uses: actions/upload-artifact@v3
        with:
          name: target-linux
          path: ./build/
    
  build-android:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build and upload
        shell: pwsh
        run: |
          export ANDROID_HOME=$HOME/.android/sdk
          ./gradlew clean android --stacktrace --info --no-daemon -x test
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/*.*
          tag: ${{ github.event.inputs.version }}
          overwrite: true
          file_glob: true
      - uses: actions/upload-artifact@v3
        with:
          name: target-android
          path: ./build/
          
  build-ios:
    runs-on: macos-latest
    needs: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and upload
        shell: pwsh
        run: ./gradlew clean createIpa --stacktrace --info --no-daemon -x test
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/*.*
          tag: ${{ github.event.inputs.version }}
          overwrite: true
          file_glob: true
      - uses: actions/upload-artifact@v3
        with:
          name: target-ios
          path: ./build/
 
