
name: release

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version'
        # Default value if no value is explicitly provided
        default: '1.0.0'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          draft: false
          prerelease: false

  build-windows:
    runs-on: windows-latest
    needs: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and upload Windows binary
        shell: pwsh
        run: ./gradlew clean packageForWindows --stacktrace --info --no-daemon -x test
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/*.*
          tag: ${{ github.event.inputs.version }}
          overwrite: true
          file_glob: true
      - uses: actions/upload-artifact@v3
        with:
          name: target-windows
          path: ./build/

  build-mac:
    runs-on: macos-latest
    needs: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and upload Mac binary
        shell: pwsh
        run: ./gradlew clean packageForMac --stacktrace --info --no-daemon -x test
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/*.*
          tag: ${{ github.event.inputs.version }}
          overwrite: true
          file_glob: true
      - uses: actions/upload-artifact@v3
        with:
          name: target-mac
          path: ./build/

  build-linux:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and upload Linux binary
        shell: pwsh
        run: ./gradlew clean packageForLinux --stacktrace --info --no-daemon -x test
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/*.*
          tag: ${{ github.event.inputs.version }}
          overwrite: true
          file_glob: true
      - uses: actions/upload-artifact@v3
        with:
          name: target-linux
          path: ./build/
